### ISSUE TITLE
Sampler の実装

### ISSUE THREAD

**Issue by shinsuke-ota** [spadi-alliance/nestdaq-user-impl#2]
- 機能
  - AMANEQ からのデータを受け取って横流し
  - Emulator を使ってデータを発生させて後段へ

- 仕様の詳細を詰める必要あり
  - [ ] AMANEQ 制御部をどうするか？
  - [ ] Sampler の共用部分があるか？　
  - [ ] 将来的には　AMANEQ 以外の　FEE に対応させる？

**Comment by sirotori1119** [comment]
・将来的にはAMANEQ 以外の　FEE に対応させる？->Generatorのベースクラスの準備でよい？

**Comment by shinsuke-ota** [comment]
読みだすデータサイズは、デフォルトを設定しておいて、パラメータで上書きできるようにする
