### ISSUE TITLE
Sink の実装

### ISSUE THREAD

**Issue by shinsuke-ota** [spadi-alliance/nestdaq-user-impl#3]
## Sink 
- 機能
  - ヘッダを書き込む
  - 受け取ったバッファを書き込む
- 制御パラメータ
  - ファイル名（ラン番号）
  - バッファーサイズ
  - ファイルパス
  - ファイル形式
  - サブネーム?
  - オーバーライドポリシー?
  - name of the input channel? 
- メタ情報をどうつけるか？
  - どんなデータが入っているか（sampler, stfb など）=>  64 bit
  - ラン番号 => 32 bit
  - スタートの時刻 => unixtime 64 bit
  - ストップの時刻 => unixtime 64 bit
  - コメント？
  - ヘッダー長も可変にして、バージョン？
  - ヘッダー長が最初にくる
  - xml にする？
  - ブロックごとの時刻を入れておくか？
    - 処理スピードを見る？

**Comment by sirotori1119** [comment]
・Sinkまでに時系列を揃えるか？->基本的には要らないが、Time frameを跨ぐ解析は必要
・N個Sinkを作るか？->まずは1つで行う。後でマージする形も可能

**Comment by nobukoba** [comment]
E16のFileSinkというのがあるらしい。これをベースにするのが良さそう。
https://github.com/igalashi/userworks/tree/main/e16/FileSink

**Comment by nobukoba** [comment]
とりあえず、メタ情報の名前と構造を考え中です。以下、たたき台の第０版。
    ヘッダーブロック長  (64bit) => unsigned long filesink_header_block_size
    どんなデータが入っているか（sampler, stfb など）(64bit) => unsigned long fairmq_device_type
    ラン番号 (32 bit) =>  unsigned int run_number
    スタートのunix 時刻 (64bit) => std::time_t start_unixtime
    ストップのunix 時刻 (64 bit) => std::time_t stop_unixtime
    コメント 256 bytes => char comments[256]

以下、今後の課題。
    ヘッダー長も可変にして、バージョン？
    ヘッダー長が最初にくる
    xml にする？
    ブロックごとの時刻を入れておくか？
        処理スピードを見る？

**Comment by shinsuke-ota** [comment]
共有ありがとうございます。
名前はキャメルケース希望です。（fairmq もそうなっている。boost はスネークケースだけど、 _ を入れるのが大変 w）
クラスのメンバーであればそれがわかるようにしておきたい。
（ROOT では変数は fXX と fieldとして、関数は大文字で始まるというのがコーディングルールとなっています。fairmq も踏襲している気がします。）

**Comment by nobukoba** [comment]
名前の命名規則、承知しました。unix 時刻の単位は秒です。

**Comment by nobukoba** [comment]
ヘッダーブロックを実装してみたのですが、以下のメンバーをもつクラスを作ったところ、このクラスのサイズがメンバー変数のそれぞれのサイズの和 292バイトにならず、296 バイトになります。

ヘッダーブロック長 (64bit)                                                   => unsigned long fFileSinkHeaderBlockSize
どんなデータが入っているか（sampler, stfb など）(64bit) => unsigned long fFairMQDeviceType
ラン番号 (32 bit)                                                                    => unsigned int fRunNumber
スタートのunix 時刻 (64bit)                                                  => std::time_t fStartUnixtime
ストップのunix 時刻 (64 bit)                                                 => std::time_t fStopUnixtime
コメント 256 bytes                                                               => char fComments[256]

おそらく、ラン番号の32bit int変数がクラスのオブジェクトになった段階で(?)パディングされて64bit分のメモリスペースを使っている模様です（参考: http://www7b.biglobe.ne.jp/~robe/cpphtml/html03/cpp03014.html）。このような実装で良いものでしょうか？解析の時に混乱しないか、ちょっと気になりました。#pragma pack を使うか、ラン番号も 64 bit にしてしまうのありですかね？

**Comment by shinsuke-ota** [comment]
おろ、そんなえげつない実装ありましたっけ。。。 unsigned int が 64bit 仕様ということではないですか？ sizeof(unsigned int) のサイズをチェックしてみてください。

**Comment by shinsuke-ota** [comment]
が、確かにホームページではそうだとおっしゃってますね。今更認識しました。ありがたや。

**Comment by shinsuke-ota** [comment]
64 bit に変更はしておいて良いと思います。
そういえば MAGIC を埋め込む必要がありますかね。
以下のようにすると little endian 仕様であればうまく変換できます。（root とかでやると数字が返ってきます。）
変換したのを埋め込むほうがよいかな。

constexpr uint64_t Magic { *(uint64_t*)(char*) "@FS-HEAD"};

**Comment by nobukoba** [comment]
データフォーマットの仕様検討TFの議論が進み、FileSinkのフォーマットも変更する必要が出てきた。とりあえず、MAGICが先にきて、その次にデータサイズがくるように変更する。さらに、footer ブロックも入れる必要あり。いつ変更するのが良いんだろうか？

**Comment by shinsuke-ota** [comment]
いま、変更してしまって良いのではないでしょうか？（解析、コードの修正がまとまって楽です。）
